{% set name = "jobard-worker-dask" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_worker_dask/-/archive/{{ version }}/jobard_worker_dask-{{ version }}.tar.gz
  sha256: c9c7e400c7353cb49e9214734a3f3757e4f24307e9552bd9cece97e26f59ab61


build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - jobard-worker-dask-swarm-setup = jobard_worker_dask.swarm:dask_setup

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - dask >=2021.10.0
    - distributed >=2021.10.0
    - cloudpickle >=2.0.0
    - click >=8.0.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - jobard_worker_dask

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_worker_dask
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Jobard dask worker initialization, used by jobard_remote_dask component.


extra:
  recipe-maintainers:
    - marie59
    - criou-cg
